### ISSUE TITLE
Add tests for provider and consumer in same project

### ISSUE THREAD

**Issue by holly-cummins** [quarkiverse/quarkus-pact#75]
This is a realistic scenario, and with such complex classloading, it's also possible it might fail.

**Comment by edeandrea** [comment]
FYI this scenario exists in the Quarkus Superheroes `rest-fights`. 

The `rest-fights` is a provider for the `ui-super-heroes` (https://github.com/quarkusio/quarkus-super-heroes/blob/main/rest-fights/src/test/java/io/quarkus/sample/superheroes/fight/ContractVerificationTests.java), yet is also a consumer for `rest-villains` (https://github.com/quarkusio/quarkus-super-heroes/blob/main/rest-fights/src/test/java/io/quarkus/sample/superheroes/fight/client/VillainConsumerContractTests.java) & `rest-heroes` (https://github.com/quarkusio/quarkus-super-heroes/blob/main/rest-fights/src/test/java/io/quarkus/sample/superheroes/fight/client/HeroConsumerContractTests.java) providers.

It _seems_ to work fine when all the `rest-fights` tests run.
